name: Code Formatting Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  prettier:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Prettier
      run: npm install --save-dev prettier @trivago/prettier-plugin-sort-imports
      
    - name: Check Prettier formatting
      run: |
        npx prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,md}" || {
          echo "❌ Code formatting issues found!"
          echo "Run 'npx prettier --write \"src/**/*.{ts,tsx,js,jsx,json,css,md}\"' to fix formatting"
          exit 1
        }
        
    - name: Check if formatting is needed
      run: |
        if ! npx prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,md}" > /dev/null 2>&1; then
          echo "::warning::Code formatting issues detected. Please run Prettier to fix formatting."
        else
          echo "✅ All files are properly formatted!"
        fi